export enum LogsObrigatorioEnum {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAIL = 'LOGIN_FAIL',
    ACCOUNT_STATE_CHANGE = 'ACCOUNT_STATE_CHANGE',
    PERMISSION_GRANTED = 'PERMISSION_GRANTED',
    PERMISSION_REVOKED = 'PERMISSION_REVOKED', 
    TENANT_CREATED = 'TENANT_CREATED',
    TENANT_SUSPENDED = 'TENANT_SUSPENDED', 
    AUDIT_REVIEW = 'AUDIT_REVIEW', 
    SUPPORT_TICKET_OPENED = 'SUPPORT_TICKET_OPENED',
    SUPPORT_TICKET_CLOSED = 'SUPPORT_TICKET_CLOSED', 
    FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED',
}